# Generated by Django 3.0.6 on 2020-05-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_counter',
            field=models.IntegerField(default=0),
        ),
    ]
