# Generated by Django 3.0.6 on 2020-05-19 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_postimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
