# Generated by Django 3.0.6 on 2020-06-12 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_post_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file',
        ),
    ]
